baseURL = "http://example.org/"
languageCode = "en-us"
title = "AlienCDH"
theme = "terminal"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Projects"
pageRef = "/projects"
weight = 20
